### ISSUE TITLE
"dbConnect is not a function" in pages/api/auth/signup.js - JustSuperHuman

### ISSUE THREAD

**Issue by JustSuperHuman** [AidanGuarniere/myChat#10]
Hey Aidan! Great work! I had an idea for a really simple overnight app but it turns out I'm horrible at React / NextJS

(I skimmed through the Udemy course) 😅

The app is running and I believe all variables are configured, but when I submit a new user at the sign up screen I get
```
error - pages\api\auth\signup.js (42:17) @ dbConnect
error - TypeError: (0 , _utils_dbConnect_js__WEBPACK_IMPORTED_MODULE_0__.dbConnect) is not a function
    at handler (webpack-internal:///(api)/./pages/api/auth/signup.js:49:73)
    at Object.apiResolver (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\api-utils\node.js:363:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\next-server.js:487:9)
    at async Object.fn (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\next-server.js:749:37)
    at async Router.execute (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\dev\next-dev-server.js:741:20)
    at async DevServer.handleRequest (C:\Users\james.TEKPREPPER\Desktop\MyGPT\Let-Me-Chat-GPT-That-For-You\node_modules\next\dist\server\base-server.js:322:20) {
  page: '/api/auth/signup'
}
  40 |   }
  41 |
> 42 |   await dbConnect();
     |                 ^
  43 |
  44 |   try {
  45 |     const result = await handlePostRequest(req, res);
```

I don't know how to debug Next at all, but it seems like it's not loading the import? I double and it seems good? Is there something else it could be?

**Comment by AidanGuarniere** [comment]
Hey! Thanks for the kind words! 

Try pulling from the main branch again and see if the error persists, you may have cloned an unstable version of the template (aka I pushed something to the main branch that I shouldn't have).

If that doesn't clear things up and you've got all the setup in place (MongoDB, Redis, .local.env file, etc... stuff in the Setup section of the README) then maybe double-check that it reads "import dbConnect" and NOT "import {dbConnect}". If that doesn't fix it either let me know👍
